"""Lay down an SRE-<service> skeleton with vendored, pinned schemas (review items S3/F13).

The output repo vendors the exact schema set + engine version it was born with into ``.sre/`` so its
own CI validates against the contract that generated it, decoupled from this repo's main. Renovate
(or a re-vendor on the next scan) bumps the pin later.
"""
from __future__ import annotations

import shutil
from pathlib import Path

from . import __version__
from .paths import data_dir

SCHEMA_DIR = data_dir("schemas")

_DIRS = [
    "metadata", "slos", "alerts/intent", "dashboards", "runbooks", "diagrams",
    ".proposed", ".sre/schemas", ".provenance",
]


def scaffold(out: str | Path, service: str, schema_dir: Path = SCHEMA_DIR) -> Path:
    root = Path(out)
    for d in _DIRS:
        (root / d).mkdir(parents=True, exist_ok=True)

    # vendor pinned schemas
    if schema_dir.is_dir():
        for s in schema_dir.glob("*.schema.json"):
            shutil.copy2(s, root / ".sre" / "schemas" / s.name)
    (root / ".sre" / "version").write_text(f"latent-sre=={__version__}\n", encoding="utf-8")

    (root / ".provenance" / "scan.yaml").write_text(
        "apiVersion: sre.latent-sre/v1\n"
        "kind: ScanProvenance\n"
        f"service: {service}\n"
        f"engineVersion: {__version__}\n"
        "needs-human-review: true\n",
        encoding="utf-8",
    )
    (root / "README.md").write_text(
        f"# SRE-{service}\n\n"
        "> Auto-generated SRE knowledge base. **AI-drafted — every artifact needs human review.**\n"
        f"> Generated by latent-sre {__version__}. See `.provenance/scan.yaml`.\n",
        encoding="utf-8",
    )
    return root
